### PR TITLE
Negative exponents and Fractional exponents

### PR DESCRIPTION
**Pull request by aliang8**
Do we want fractions to be matched by a single identifier (#b) or should we match it as division (#b / #c)?

### CODE REVIEW

**Comment by k4b7** [comment]
> Do we want fractions to be matched by a single identifier (#b) or should we match it as division (#b / #c)?

If you want to manipulate the fraction inside a rewrite pattern then you'll have to use #b / #c.

**Comment by k4b7** [comment]
Looks good, but there merge conflicts you'll have to resolve.

**Comment by aliang8** [comment]
Fixed.

**Comment by k4b7** [comment]
Thanks.

**Pull request merged**
